# Generated by Django 4.1.2 on 2023-08-03 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=200)),
                ('average_rating', models.FloatField(default=0.0)),
                ('is_problem', models.BooleanField(default=False)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.keyword')),
            ],
        ),
        migrations.CreateModel(
            name='MyLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revisit', models.BooleanField(default=False)),
                ('done', models.BooleanField(default=False)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.keyword')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.link')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
