# Generated by Django 4.1.2 on 2023-08-03 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_link_rated_link_total_ratings_link_total_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='mylink',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
